/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author Francisco
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCanciones = new javax.swing.JButton();
        botonPeliculas = new javax.swing.JButton();
        botonGeneros = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AMANTE DE LA MUSICA Y EL CINE");
        setName("VentanaPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        botonCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Canciones.png"))); // NOI18N
        botonCanciones.setBorder(null);
        botonCanciones.setBorderPainted(false);
        botonCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCanciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCanciones.setIconTextGap(-3);
        botonCanciones.setInheritsPopupMenu(true);
        botonCanciones.setOpaque(false);
        botonCanciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Canciones2.png"))); // NOI18N
        botonCanciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonCanciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancionesActionPerformed(evt);
            }
        });

        botonPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Peliculas.png"))); // NOI18N
        botonPeliculas.setBorder(null);
        botonPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPeliculas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPeliculas.setIconTextGap(-3);
        botonPeliculas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Peliculas2.png"))); // NOI18N
        botonPeliculas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonPeliculas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPeliculasActionPerformed(evt);
            }
        });

        botonGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Generos.png"))); // NOI18N
        botonGeneros.setBorder(null);
        botonGeneros.setBorderPainted(false);
        botonGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGeneros.setIconTextGap(-3);
        botonGeneros.setOpaque(false);
        botonGeneros.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Generos2.png"))); // NOI18N
        botonGeneros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonGeneros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setIconTextGap(-3);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(botonCanciones)
                .addGap(66, 66, 66)
                .addComponent(botonPeliculas)
                .addGap(58, 58, 58)
                .addComponent(botonGeneros)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCanciones)
                    .addComponent(botonPeliculas)
                    .addComponent(botonGeneros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleName("Salir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancionesActionPerformed
        VentanaCanciones ventanaCanciones = new VentanaCanciones();
        ventanaCanciones.setVisible(true);
    }//GEN-LAST:event_botonCancionesActionPerformed

    private void botonPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPeliculasActionPerformed
        VentanaPeliculas ventanaPeliculas = new VentanaPeliculas();
        ventanaPeliculas.setVisible(true);
    }//GEN-LAST:event_botonPeliculasActionPerformed

    private void botonGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerosActionPerformed
        VentanaGeneros ventanaGeneros = new VentanaGeneros();
        ventanaGeneros.setVisible(true);
    }//GEN-LAST:event_botonGenerosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCanciones;
    private javax.swing.JButton botonGeneros;
    private javax.swing.JButton botonPeliculas;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
